// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3d4L0EsQt3hu5cEMqWu4-gh8a9vJJ0eo',
    appId: '1:997774580125:web:0112678e9898d23080b774',
    messagingSenderId: '997774580125',
    projectId: 'chatapp-90219',
    authDomain: 'chatapp-90219.firebaseapp.com',
    databaseURL: 'https://chatapp-90219-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-90219.appspot.com',
    measurementId: 'G-LWVQPRC93Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA283UgYyyYbVFZT4ihdQ5NoupEWUrItSI',
    appId: '1:997774580125:android:d500b61db58721e880b774',
    messagingSenderId: '997774580125',
    projectId: 'chatapp-90219',
    databaseURL: 'https://chatapp-90219-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-90219.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmuvujFlzSwRqvCRVJwZtDQSUn73FtHgo',
    appId: '1:997774580125:ios:a19883eed01f2f8b80b774',
    messagingSenderId: '997774580125',
    projectId: 'chatapp-90219',
    databaseURL: 'https://chatapp-90219-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-90219.appspot.com',
    iosClientId: '997774580125-eo1taf7dbekipl9mvs4rp2ipsd2f63pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmuvujFlzSwRqvCRVJwZtDQSUn73FtHgo',
    appId: '1:997774580125:ios:a19883eed01f2f8b80b774',
    messagingSenderId: '997774580125',
    projectId: 'chatapp-90219',
    databaseURL: 'https://chatapp-90219-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-90219.appspot.com',
    iosClientId: '997774580125-eo1taf7dbekipl9mvs4rp2ipsd2f63pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
